#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# Check_MK Check JBoss
#
# Copyright 2019, Yannis Mitsos <yannis@mitsos.net>
#
# Permission is hereby granted, free of charge, to any person obtaining a 
# copy of this software and associated documentation files (the "Software"), 
# to deal in the Software without restriction, including without limitation 
# the rights to use, copy, modify, merge, publish, distribute, sublicense, 
# and/or sell copies of the Software, and to permit persons to whom the 
# Software is furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in 
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS 
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING 
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
# DEALINGS IN THE SOFTWARE.

def check_jboss_arguments(params):

    args = ""

    if "action" in params:
        args += "-A %s " % quote_shell_string(params["action"])
    else:
        args += "-A server_status"

    if "port" in params:
        args += "-P %s " % (params["port"])
    else:
        args += "-P 9990"

    if "user" in params:
        args += "-u %s " % quote_shell_string(params["user"])

    if "password" in params:
        args += "-p %s " % quote_shell_string(params["password"][1])

    if "queue_name" in params:
        args += "-q %s " % quote_shell_string(params["queue_name"])

    if "queue_type" in params:
        args += "-Q %s " % quote_shell_string(params["queue_type"])

    if "datasource" in params:
        args += "-d %s " % quote_shell_string(params["datasource"])

    if "ds_stat_type" in params:
        args += "-s %s " % quote_shell_string(params["ds_stat_type"])

    if "thread_stat_type" in params:
        args += "-t %s " % quote_shell_string(params["thread_stat_type"])

    return args
#enddef

active_check_info['jboss'] = {
    "command_line"           : '$USER2$/nagios-plugin-jbossas7/check_jbossas7.py -H $HOSTADDRESS$ $ARG1$',
    #"command_line"           : '$USER2$/nagios-plugin-jbossas7/check_jbossas7.py -H $HOSTADDRESS$ -A $ARG1$ -P 9990 -u $ARG3$ -p $ARG4$ -W $ARG5$ -C $ARG6$',
    "argument_function"      : check_jboss_arguments,
    "service_description"    : lambda args: args["description"],
    "has_perfdata"           : False,
}
